global:
  scrape_interval: 60s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

  # Attach these extra labels to all timeseries collected by this Prometheus instance.
  # external_labels:
  #   monitor: "codelab-monitor"

rule_files:
  - "first.rules"

scrape_configs:
  - job_name: "prometheus"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 60s
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/tls.crt
      key_file: /etc/prometheus/certs/tls.key
      insecure_skip_verify: false
      # server_name: << INSERT SERVER NAME >>
    basic_auth:
      username: admin
      password_file: "/etc/prometheus/secret.txt"

    static_configs:
      - targets: ["localhost:9090"]
        labels:
          group: "production"
          type: "internal"

  - job_name: 'grafana'
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/tls.crt
      key_file: /etc/prometheus/certs/tls.key
      insecure_skip_verify: false
      # server_name: << INSERT SERVER NAME >>
    scrape_interval: 15s
    scrape_timeout: 5s
    basic_auth:
      username: admin
      password_file: "/etc/prometheus/secret.txt"

    static_configs:
      - targets: ['grafana:3000']

  # - job_name: "blackbox"
  #   static_configs:
  #     - targets: ["172.18.0.4:9115"]
  #       labels:
  #         group: "production"
  #         type: "internal"

  - job_name: "ping"
    static_configs:
      - targets: ["ping_exporter:9427"]
        labels:
          group: "production"
          type: "internal"

  - job_name: "node"
    static_configs:
      - targets: ["172.18.0.1:9100"]
        labels:
          group: "production"
          type: "internal"

  - job_name: "snmp_interface"
    file_sd_configs:
      - files:
          - "snmp_targets.json"
        refresh_interval: 120s
    scrape_interval: 20s
    scrape_timeout: 10s
    metrics_path: /snmp
    params:
      auth: [public_v3]
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.18.0.4:9116 # The SNMP exporter's real hostname:port.

  - job_name: "snmp_extended"
    file_sd_configs:
      - files:
          - "snmp_targets.json"
    scrape_interval: 60s
    scrape_timeout: 30s
    metrics_path: /snmp
    params:
      auth: [public_v3]
      module: [mikrotik, hrSystem, hrDevice, hrStorage]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.18.0.4:9116 # The SNMP exporter's real hostname:port.

  # Global exporter-level metrics
  - job_name: "snmp_exporter"
    static_configs:
      - targets: ["snmp_exporter:9116"]

  - job_name: "external"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 60s

    file_sd_configs:
      - files:
          - "targets.json"
        refresh_interval: 120s
