apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: https://prometheus:$PROM_PORT
    isDefault: true
    access: proxy
    editable: true
    # uncomment if prom has basicAuth ans set password
    basicAuth: true
    basicAuthUser: $GF_SECURITY_ADMIN_USER
    secureJsonData:
      basicAuthPassword: $GF_SECURITY_ADMIN_PASSWORD
      #  tlsCACert: $__file{/certs/tls.crt}
      tlsClientCert: $__file{/certs/tls.crt}
      tlsClientKey: $__file{/certs/tls.key}
    # jsonData:
    #   tlsAuth: <<true or false>> -- false by default
    #   tlsAuthWithCACert: <<true or false>> -- false by default
    #   serverName: <<server name that matches in certificate for tlsAuthWithCACert>>
    # <string> json object of data that will be encrypted.
