apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:$PROM_PORT
    isDefault: true
    access: proxy
    editable: true
    # uncomment if prom has basicAuth ans set password
    basicAuth: true
    basicAuthUser: $GF_SECURITY_ADMIN_USER
    secureJsonData:
      basicAuthPassword: $GF_SECURITY_ADMIN_PASSWORD
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: "2.50.1"
      cacheLevel: Medium
    #  tlsAuthWithCACert: <<true or false>> -- false by default
