apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true
    # uncomment if prom has basicAuth ans set password
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: defaultpassword
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: "2.50.1"
      cacheLevel: Medium
    #  tlsAuthWithCACert: <<true or false>> -- false by default
